# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
# [character]      # The name of the module we are configuring is "character"
# symbol = "➜"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"arn:aws:eks:us-west-2:680008785996:cluster/rtw" = "rtw-dev"

[directory]
truncate_to_repo = false

[hostname]
disabled = true

[username]
disabled = true
